# A generic, single database configuration.

[alembic]
# Yahan hum alembic ko bata rahe hain ki hamari environment aur scripts kahan hain
script_location = app/db

# Root directory ko path me add karne ke liye
prepend_sys_path = .

# Logging on rakhne ke liye

; Yeh debugging ke liye hai. Agar yeh True hai, toh jab bhi database update hoga,
;  terminal par tumhe saari raw SQL queries (CREATE TABLE..., ALTER TABLE...) print hoti hui dikhengi.
sqlalchemy.echo = True

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
;   formatters do formatting  of jo bhi terminal pe chalega when we run alembic commands
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S