"""create_legalcase_table

Revision ID: 17bf40c73296
Revises: 83c1f2e520ec
Create Date: 2026-05-30 23:09:18.529266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17bf40c73296'
down_revision = '83c1f2e520ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legalcase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lawyer_approved_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legalcase_id'), 'legalcase', ['id'], unique=False)
    op.create_table('legalsection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('ipc_section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bns_section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_lawyer_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['legalcase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legalsection_id'), 'legalsection', ['id'], unique=False)
    op.drop_index(op.f('ix_ips_section_section_code'), table_name='ips_section')
    op.drop_table('ips_section')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('phone_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'phone_no')
    op.drop_column('user', 'name')
    op.drop_column('user', 'is_deleted')
    op.create_table('cases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('cases_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cases_pkey'))
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_table('ips_section',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('section_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('penalty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('ips_section_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ips_section_pkey'))
    )
    op.create_index(op.f('ix_ips_section_section_code'), 'ips_section', ['section_code'], unique=True)
    op.drop_index(op.f('ix_legalsection_id'), table_name='legalsection')
    op.drop_table('legalsection')
    op.drop_index(op.f('ix_legalcase_id'), table_name='legalcase')
    op.drop_table('legalcase')
    # ### end Alembic commands ###