"""move lawyer verified to section

Revision ID: 52795fe26c69
Revises: 7f1650ba3bef
Create Date: 2026-06-07 21:58:32.998297

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '52795fe26c69'
down_revision = '7f1650ba3bef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###