"""add soft delete fields to base

Revision ID: 7ae0cc35cfdb
Revises: 6b888cda3aff
Create Date: 2026-06-06 22:51:21.409353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7ae0cc35cfdb'
down_revision = '6b888cda3aff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referencecase', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_referencecase_case_id'), 'referencecase', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referencecase_case_id'), table_name='referencecase')
    op.drop_column('referencecase', 'deleted_at')
    # ### end Alembic commands ###