"""added has_lawyer_verified to legalsection

Revision ID: 7f1650ba3bef
Revises: 935fee312e88
Create Date: 2026-06-07 21:46:29.020496

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7f1650ba3bef'
down_revision = '935fee312e88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legalcase', 'is_sections_approved')
    op.add_column('legalsection', sa.Column('has_lawyer_verified', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legalsection', 'has_lawyer_verified')
    op.add_column('legalcase', sa.Column('is_sections_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###