"""add final report fields

Revision ID: 16cdd22962de
Revises: e99f9bc4b8c6
Create Date: 2026-06-07 16:53:47.842446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cdd22962de'
down_revision: Union[str, Sequence[str], None] = 'e99f9bc4b8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('final_summary', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('final_reasoning', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('report_status', sa.String(), nullable=True))
    # op.alter_column('ipc_sections', 'reason',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipc_sections', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cases', 'report_status')
    op.drop_column('cases', 'final_reasoning')
    op.drop_column('cases', 'final_summary')
    # ### end Alembic commands ###
