"""final base model fix

Revision ID: cd936a760d37
Revises: a4727694f67a
Create Date: 2026-06-01 00:10:40.149854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd936a760d37'
down_revision: Union[str, Sequence[str], None] = 'a4727694f67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('cases', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cases', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('legal_sections', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('legal_sections', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('legal_sections', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('legal_sections', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('legal_sections', 'case_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('legal_sections', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('legal_sections', 'source',
               existing_type=postgresql.ENUM('lawyer', 'llm', name='sectionsource'),
               nullable=False)
    op.drop_column('legal_sections', 'is_approved')
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'phone_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.add_column('legal_sections', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('legal_sections', 'source',
               existing_type=postgresql.ENUM('lawyer', 'llm', name='sectionsource'),
               nullable=True)
    op.alter_column('legal_sections', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('legal_sections', 'case_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('legal_sections', 'deleted_at')
    op.drop_column('legal_sections', 'is_deleted')
    op.drop_column('legal_sections', 'updated_at')
    op.drop_column('legal_sections', 'created_at')
    op.alter_column('cases', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('cases', 'deleted_at')
    op.drop_column('cases', 'is_deleted')
    # ### end Alembic commands ###
